### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by IzzySoft** [YourDroid/YourDroid#17]
Is there any more detailed description of what *YourDroid* does and how? For example: Does it install Android *inside* the currently used OS (like an app or emulator), or alongside? Does it require a separate partition? Does it overwrite/replace the current OS?

Maybe you could add some additional lines to the central `Readme.md` file?

**Comment by ProfiGMan** [comment]
Hello! Thanks for your comment! I'll fix it in a little.

**Comment by ProfiGMan** [comment]
I've just edited it. Is there information enough?

**Comment by IzzySoft** [comment]
Definitely much better! Thanks a lot! Especially installing to a dir sounds interesting. Open questions:

* which version of Android does it install (or can the user chose that)?
* it should be possible to create a VM with a basic Debian, and then install YourDroid into that (e.g. into `/opt/yourdroid`) if one doesn't want to dual-boot the PC, right?
* is architecture (32bit/64bit) any issue here? As you mention android-x86, I conclude ARM etc. are not suitable, right?

**Comment by ProfiGMan** [comment]
Can you look up README.md to find mistakes? My english is bad, so i could make mistakes

**Comment by ProfiGMan** [comment]
I answered all of your questions at README.md

**Comment by IzzySoft** [comment]
It's well understandable. Some minor corrections if you wish:

> … YourDroid installs Andoid x86 and adds it to the bootloader of the main OS or installs …

> … You can choose one on a web site of android x86 …

> … You can download an ISO-image with a Linux distro …

> … You can create a VM and install a Linux distro (recommended) or Windows into it, then install Android to it to make it a dualboot system if you like …

> It automatically **detects** the features of your PC

Thanks a lot!!! :+1:

PS: Added it to [my list here](https://android.izzysoft.de/applists/category/named/emulators) (look at the end of the page) :wink:

**Comment by ProfiGMan** [comment]
Thank you too a lot! (and your english is great)
