### ISSUE TITLE
beta3 stuck on creating bootloader

### ISSUE THREAD

**Issue by vadimlitvinenko87** [YourDroid/YourDroid#18]
Windows7 x64 updated december 2018 BIOS (no UEFI mode)
Log file archived by 7z
https://send.firefox.com/download/59f0c42444/#FqWyYbCSGHLklk0cpOG4CA
yourdroid.v2.0-beta.3

TIME: 17:34:11 FILE: ..\source\cmd.cpp LINE: 71 DEBUG: Creating filesystem with parameters:
    Size: 16777216000
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8192
    Inode size: 256
    Journal blocks: 32768
    Label: 
    Blocks: 4096000
    Block groups: 125
    Reserved block group size: 999
Created filesystem with 11/1024000 inodes and 107031/4096000 blocks

TIME: 17:34:11 FILE: ..\source\window.cpp LINE: 444 DEBUG: Installing bootloader...

TIME: 17:34:11 FILE: ..\source\install.cpp LINE: 121 DEBUG: Registering to bootloader...

TIME: 17:34:11 FILE: ..\source\install.cpp LINE: 125 DEBUG: Registering to bootmgr

TIME: 17:34:11 FILE: ..\source\install.cpp LINE: 134 DEBUG: Setting up bootmgr

TIME: 17:34:11 FILE: ..\source\install.cpp LINE: 144 DEBUG: c:/yourdroid_boot exists

TIME: 17:34:11 FILE: ..\source\install.cpp LINE: 147 DEBUG: c:/yourdroid_boot/ANDROIDX86 doesn't exist

TIME: 17:34:11 FILE: ..\source\global.h LINE: 32 DEBUG: Making dir c:/yourdroid_boot/ANDROIDX86

TIME: 17:34:11 FILE: ..\source\global.h LINE: 34 DEBUG: Made successfully

TIME: 17:34:11 FILE: ..\source\install.cpp LINE: 170 DEBUG: Selecting grub4dos file name...

TIME: 17:34:11 FILE: ..\source\install.cpp LINE: 184 DEBUG: there's no gr_?

---------------------------------------------------------------------------------------------------------------
than reapeted 1000 times @TIME: 17:34:11 FILE: ..\source\install.cpp LINE: 184 DEBUG: there's no gr_@
Window of application do not answer anymore yourdroid_boot folder is clear and has no files. No BCD booting line added. Looks like program cant take access to folder or something similar. All folders of YourDroid is with read\write permission and run in admin mode.

**Comment by ProfiGMan** [comment]
Well, this is because it doesn't support BIOS yet. And I regret to say it will probably never do since this project is sort of dead because I couldn't solve all the problems and I've lost any motivation.
Thanks for the bug report though

**Comment by vadimlitvinenko87** [comment]
Anyway, thanks for answer.

**Comment by ProfiGMan** [comment]
Hi! I'm back to the project and now the program fully supports windows bios and uefi. So if you're still interested in it, go ahead and try to use it. It should work now
